---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.12.0"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-souvap.yaml"
      - "jobs/package-and-publish-helm-charts-souvap.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "selfservice-listener"
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE_PATH: "docker/selfservice-listener/Dockerfile"
  - IMAGE_NAME:
      - "selfservice-invitation"
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE_PATH: "docker/selfservice-invitation/Dockerfile"

container-build:
  parallel:
    matrix: *build-matrix

container-generate-sbom:
  parallel:
    matrix: *build-matrix

container-sign:
  parallel:
    matrix: *build-matrix

container-security-scan:
  parallel:
    matrix: *build-matrix

push-image-souvap:
  parallel:
    matrix: *build-matrix

container-sign-souvap:
  parallel:
    matrix: *build-matrix

...
