{{/*
SPDX-FileCopyrightText: 2025 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}

{{- if not (.Values.provisioningApi.auth.existingSecret).name }}

{{- $secretName := include "nubus-common.secrets.name" ( dict "defaultNameSuffix" "provisioning-api" "context" . ) }}
{{- $username := tpl (
  required
    "A Provisioning API username is required, see parameter provisioningApi.auth.username"
    .Values.provisioningApi.auth.username
  ) . }}
{{- $password := include "nubus-common.secrets.passwords.manage"
  (dict
    "secret" $secretName
    "key" "password"
    "username" "nubus"
    "site" "selfservice-listener"
    "providedValues" (list "provisioningApi.auth.password")
    "context" .
  )
}}
---
kind: "Secret"
apiVersion: "v1"
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- $extraAnnotations := dict }}
  {{- if (.Values.global.secrets).keep }}
    {{- $_ := set $extraAnnotations "helm.sh/resource-policy" "keep" }}
  {{- end }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list $extraAnnotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
stringData:
  password: {{ $password | quote }}
  registration: |
    {
      "name": {{ $username | toJson }},
      "realms_topics": [
        {
          "realm": "udm",
          "topic": "users/user"
        }
      ],
      "request_prefill": true,
      "password": {{ $password | toJson }}
    }

{{- end }}
