# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  serviceName: {{ include "common.names.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
        checksum/secret: '{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}'
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: '{{ .Chart.Name }}'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ coalesce .Values.selfserviceListener.image.registry .Values.global.imageRegistry }}/{{ .Values.selfserviceListener.image.repository }}{{ if .Values.selfserviceListener.image.sha256 }}@sha256:{{ .Values.selfserviceListener.image.sha256 }}{{ else }}:{{ .Values.selfserviceListener.image.tag }}{{ end }}'
          imagePullPolicy: '{{ .Values.global.imagePullPolicy }}'
          env:
            - name: "UMC_ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ include "selfserviceListener.umcAdminPasswordSecret.name" . }}"
                  key: "{{ include "selfserviceListener.umcAdminPasswordSecret.key" . }}"
          envFrom:
            - configMapRef:
                name: '{{ include "common.names.fullname" . }}'
          volumeMounts:
            {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
            - name: "secrets"
              mountPath: "{{ .Values.selfserviceListener.secretMountPath }}"
            {{- else }}
            {{- include "selfserviceListener.secretVolumeMounts" . | nindent 12 }}
            {{- end }}
            - name: "data"
              mountPath: "/var/lib/univention-directory-listener"
            - name: "shared"
              mountPath: "/var/cache/listener"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: '{{ .Chart.Name }}-invitation'
          # command: ["/bin/bash"]
          # args: [sleep", "60000"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ coalesce .Values.selfserviceInvitation.image.registry .Values.global.imageRegistry }}/{{ .Values.selfserviceInvitation.image.repository }}{{ if .Values.selfserviceInvitation.image.sha256 }}@sha256:{{ .Values.selfserviceInvitation.image.sha256 }}{{ else }}:{{ .Values.selfserviceInvitation.image.tag }}{{ end }}'
          imagePullPolicy: '{{ .Values.global.imagePullPolicy }}'
          envFrom:
            - configMapRef:
                name: '{{ include "common.names.fullname" . }}'
          volumeMounts:
            {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
            - name: "secrets"
              mountPath: "{{ .Values.selfserviceListener.secretMountPath }}"
            {{- else }}
            {{- include "selfserviceListener.secretVolumeMounts" . | nindent 12 }}
            {{- end }}
            - name: "shared"
              mountPath: "/var/cache/listener"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: wait-for-ldap
          command: ["/bin/bash", "/scripts/wait-for-ldap.sh"]
          image: '{{ coalesce .Values.waitForDependency.image.registry .Values.global.imageRegistry }}/{{ .Values.waitForDependency.image.repository }}{{ if .Values.waitForDependency.image.sha256 }}@sha256:{{ .Values.waitForDependency.image.sha256 }}{{ else }}:{{ .Values.waitForDependency.image.tag }}{{ end }}'
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "common.names.fullname" . }}
          volumeMounts:
            {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
            - name: "secrets"
              mountPath: "{{ .Values.selfserviceListener.secretMountPath }}"
            {{- else }}
            {{- include "selfserviceListener.secretVolumeMounts" . | nindent 12 }}
            {{- end }}
            - name: "wait-for-ldap"
              mountPath: "/scripts"
          resources:
            {{- toYaml .Values.resourcesWaitForDependency | nindent 12 }}
      volumes:
        {{- if and .Values.mountSecrets (not .Values.global.nubusDeployment) }}
        - name: "secrets"
          secret:
            secretName: {{ include "common.names.fullname" . | quote }}
        {{- else }}
        {{- if (include "selfserviceListener.ldap.credentialSecret.name" . ) }}
        - name: {{ printf "%s-volume" (include "selfserviceListener.ldap.credentialSecret.name" . ) | quote }}
          secret:
            secretName: {{ (include "selfserviceListener.ldap.credentialSecret.name" . ) | quote }}
        {{- end }}
        {{- if (include "selfserviceListener.ldap.tlsSecret.name" . ) }}
        - name: {{ printf "%s-volume" (include "selfserviceListener.ldap.tlsSecret.name" . ) | quote }}
          secret:
            secretName: {{ (include "selfserviceListener.ldap.tlsSecret.name" . ) | quote }}
        {{- end }}
        {{- end }}
        - name: wait-for-ldap
          configMap:
            name: {{ include "common.names.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: "data"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "1Gi"
  - metadata:
      name: "shared"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "1Gi"

...
