# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: v2
name: "selfservice-consumer"
description: "The selfservice consumer for handling user invites"

type: "application"

version: "0.11.3"

appVersion: "0.0.1"

dependencies:
  - name: "nubus-common"
    version: "0.21.0"
    repository: "oci://artifacts.software-univention.de/nubus/charts"
