# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

apiVersion: v2
name: "selfservice-consumer"
description: "The selfservice consumer for handling user invites"

type: "application"

version: "0.11.3"

appVersion: "0.0.1"

dependencies:
  - name: "common"
    repository: "oci://gitregistry.knut.univention.de/univention/customers/dataport/upx/common-helm/helm"
    version: "^0.2.0"

...
