# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
provisioningApi:
  auth:
    username: "username"
    existingSecret:
      name: "custom-secret-name"
      keyMapping:
        password: "custom-secret-key"
  connection:
    baseUrl: "http://test-provisioning-api"
umc:
  auth:
    password: "password"
    username: "username"
  connection:
    baseUrl: "http://test-umc-server"

...
