# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
provisioningApi:
  auth:
    password: "linter-password"
  connection:
    url: "http://test-provisioning-api"

umc:
  auth:
    password: "linter-password"
  connection:
    url: "http://test-umc-server"
